### ISSUE TITLE
Define models (Sequelize)

### ISSUE THREAD

**Issue by siwinlo** [The-Buckbeaks/GraceShopper#4]
## In database (Petra)
- [x] seed data of store inventory (plants)
- [x] seed data of users (users)
- [x] seed data of orders with association to users

## Sequelize (Siwin)
- [x] define "plants" model
- [x] define "user" model
- [x] define "orders" model

**Comment by petradish** [comment]
Hey! I am getting an error in the associations of many to many (plant/order) - can we comment this out for now?

**Comment by petradish** [comment]
Also, in the Order model, items is an Array of Text. In the seed file, I made items an Array of Objects, that contain keys of 'name' and 'quantity' for the plants

**Comment by siwinlo** [comment]
Hi Petra! 

- I can comment out the associations for plants and users for now! 
- I don't think we can have arrays of objects in Sequelize, but we can talk about this in our meeting about the cart because this might be a cart thing rather than an orders model thing?
