### ISSUE TITLE
I want my cart to clear after I submit it.

### ISSUE THREAD

**Issue by martha-ivana** [The-Buckbeaks/GraceShopper#56]
## USER STORY

As a user or as a guest, I want to be able to clear my cart.

## IMPLEMENTATION

- [x] Add clear cart button to cart component
- [x] Clear cart thunk, action creator, action type

**Comment by siwinlo** [comment]
Ack, I found a bug in so far as the cart appears to clear, but then repopulates when the user navigates away from the store and back. Will reopen this and debug after I finish writing the README.md file
