### ISSUE TITLE
As a user, I want to be able to add quantities of an item to my cart.

### ISSUE THREAD

**Issue by martha-ivana** [The-Buckbeaks/GraceShopper#57]
## USER STORY

As a user or as a guest, I want to be able to add a certain quantity of an item to the cart.

## IMPLEMENTATION

- [ ] Decrease quantity on plant model
- [X] Adjust additem thunk if needed to reflect quantity props
- [X] Adjust put route in /orders to alter quantity on order
- [X] Create dropdown menu for selecting quantity

**Comment by petradish** [comment]
Hey! The platform looks so good!! Could you also pass the additem/quantity editor down to the single plant view when you click in for description? =D!
